SUPABASE_URL = "https://daekeolxsitmeurcosnd.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhZWtlb2x4c2l0bWV1cmNvc25kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNDIxNDQsImV4cCI6MjA2NDgxODE0NH0.kYG0iWhxcUX53KqjQ7HsLCeHCo31iRo4M3jDslLNg1c"

# Configurações da Iugu (opcional - pode ser inserido via interface)
IUGU_API_TOKEN = "433118AEADA80C229DB09897CAA5D8043FCBADD50A785D863C54195C6C3784E8"

# Configurações de ambiente
ENVIRONMENT = "production"  # ou "development"
DEBUG = false